export const BUBBLE_COLOR_PRIMARY = 'BUBBLE_COLOR_PRIMARY'
export const BUBBLE_COLOR_SECONDARY = 'BUBBLE_COLOR_SECONDARY'
export const BUBBLE_COLOR_LIGHT = 'BUBBLE_COLOR_LIGHT'

export const BUBBLE_SIZE_SMALL = 'BUBBLE_SIZE_SMALL'
export const BUBBLE_SIZE_MEDIUM = 'BUBBLE_SIZE_MEDIUM'
export const BUBBLE_SIZE_LARGE = 'BUBBLE_SIZE_LARGE'
