export const BUTTON_SIZE_SMALL = 'BUTTON_SIZE_SMALL'
export const BUTTON_SIZE_MEDIUM = 'BUTTON_SIZE_MEDIUM'
export const BUTTON_SIZE_LARGE = 'BUTTON_SIZE_LARGE'

export const BUTTON_COLOR_PRIMARY = 'BUTTON_COLOR_PRIMARY'
export const BUTTON_COLOR_SECONDARY = 'BUTTON_COLOR_SECONDARY'

export const BUTTON_VARIANT_PRIMARY = 'BUTTON_VARIANT_PRIMARY'
export const BUTTON_VARIANT_OUTLINE = 'BUTTON_VARIANT_OUTLINE'
